// resources/js/react/EntityLink.tsx
import type { FeedEntity } from '../shared/types';
import { useFeedOptions } from './context';
import { entityLink, linkProps } from '../shared/link';
export default function EntityLink({
    entity,
    fallback,
}: {
    entity: FeedEntity | null;
    fallback?: string;
}) {
    const { FEED_LINK: Link = 'a' } = useFeedOptions();
    const tombstone = entity?.tombstone;
    const noun = tombstone
        ? `removed ${tombstone.formerType.replace(/[._-]/g, ' ')}`
        : '';
    const label = !entity
        ? (fallback ?? 'something')
        : tombstone
          ? (entity.label ?? `${/^[aeiou]/i.test(noun) ? 'an' : 'a'} ${noun}`)
          : (entity.label ?? 'Something');
    const classes =
        'sf-entity font-medium text-foreground no-underline underline-offset-2 hover:underline';
    // Core 0.17's `link`, or 0.16's `url`, `modal` and `attributes`.
    const link = entityLink(entity);
    if (link) {
        // `modal` belongs to a host router component, rather than the native anchor.
        return (
            <Link {...linkProps(link, Link)} className={classes}>
                {label}
            </Link>
        );
    }
    return (
        <span
            className={`${classes}${tombstone ? ' sf-entity--tombstone text-muted-foreground font-normal' : !entity?.label ? ' sf-entity--unknown italic text-muted-foreground font-normal' : ''}`}
        >
            {label}
        </span>
    );
}

// resources/js/vue/EntityLink.vue
<script setup lang="ts">
import { computed, inject } from 'vue';
import { FEED_LINK } from './keys';
import { entityLink, linkProps } from '../shared/link';
import type { FeedEntity } from '../shared/types';

const props = defineProps<{
    entity: FeedEntity | null;
    /** Rendered when the entity itself is null (e.g. an anonymous actor). */
    fallback?: string;
}>();

const linkComponent = inject(FEED_LINK, 'a');

const words = (type: string) => type.replace(/[._-]/g, ' ');
const article = (noun: string) => (/^[aeiou]/i.test(noun) ? 'an' : 'a');

/**
 * A tombstone is a deleted entity. The payload gives the facts (the former
 * type, and the label only when the model kept it); the wording is this kit's
 * own choice, as it would be any renderer's.
 */
const tombstone = computed(() => props.entity?.tombstone ?? null);

// Core 0.17's `link`, or 0.16's `url`, `modal` and `attributes`.
const link = computed(() => entityLink(props.entity));

// Degraded entities (no snapshot yet) have a null label; render a neutral
// placeholder derived from the type so the sentence still reads.
const label = computed(() => {
    if (!props.entity) {
        return props.fallback ?? 'something';
    }

    if (tombstone.value) {
        const noun = `removed ${words(tombstone.value.formerType)}`;

        return props.entity.label ?? `${article(noun)} ${noun}`;
    }

    // Core's degraded fallback: a missing label reads as "Something" (storyfeed::feed.something).
    return props.entity.label ?? 'Something';
});
</script>

<template>
    <component
        :is="linkComponent"
        v-if="link"
        v-bind="linkProps(link, linkComponent)"
        class="sf-entity font-medium text-foreground no-underline underline-offset-2 hover:underline"
    >
        {{ label }}
    </component>
    <span
        v-else
        class="sf-entity font-medium text-foreground no-underline underline-offset-2 hover:underline"
        :class="{
            'sf-entity--tombstone text-muted-foreground font-normal': tombstone,
            'sf-entity--unknown italic text-muted-foreground font-normal': !tombstone && !entity?.label,
        }"
    >
        {{ label }}
    </span>
</template>
