// resources/js/react/FeedMeta.tsx
import { Fragment, isValidElement } from 'react';
import type { ReactNode } from 'react';
import { leftoverRoles } from '../shared/meta';
import type { FeedNode } from '../shared/types';
import { EntityList } from './FeedHeadline';
function hasContent(node: ReactNode): boolean {
    if (node === null || node === undefined || typeof node === 'boolean') return false;
    if (typeof node === 'string') return Boolean(node.trim());
    if (Array.isArray(node)) return node.some(hasContent);
    if (isValidElement<{ children?: ReactNode }>(node) && (node.type === Fragment || typeof node.type === 'string')) return hasContent(node.props.children);
    return true;
}
export default function FeedMeta({
    node,
    templates,
    children,
}: {
    node: FeedNode;
    templates: (string | null | undefined)[];
    children?: ReactNode;
}) {
    const roles = leftoverRoles(node, templates);
    if (!roles.length && !hasContent(children)) return null;
    return (
        <div className="sf-meta mt-0.5 text-xs leading-[1.5] text-muted-foreground [overflow-wrap:anywhere] [&_.sf-entity]:text-inherit [&_.sf-entity]:font-normal">
            {children}
            {roles.map((part) => (
                <Fragment key={part.role}>
                    {' · '}
                    <span className="sf-meta__role">
                        {part.word + ' '}
                        <EntityList
                            entities={part.entities}
                            overflow={part.overflow}
                        />
                    </span>
                </Fragment>
            ))}
        </div>
    );
}

// resources/js/vue/FeedMeta.vue
<script setup lang="ts">
import { Comment, Fragment, Text, computed, useSlots } from 'vue';
import type { VNode } from 'vue';

import EntityLink from './EntityLink.vue';
import { leftoverRoles } from '../shared/meta';
import type { FeedNode } from '../shared/types';
const props = defineProps<{
    node: FeedNode;
    templates: (string | null | undefined)[];
}>();
const slots = useSlots();
function hasContent(nodes: VNode[]): boolean {
    return nodes.some((node) => {
        if (node.type === Comment) {
            return false;
        }

        if (node.type === Fragment || typeof node.type === 'string') {
            return Array.isArray(node.children)
                ? hasContent(node.children as VNode[])
                : Boolean(node.children);
        }

        if (node.type === Text) {
            return Boolean(String(node.children ?? '').trim());
        }

        return true;
    });
}
const roles = computed(() => leftoverRoles(props.node, props.templates));
</script>

<template>
    <div
        v-if="roles.length || hasContent(slots.default?.() ?? [])"
        class="sf-meta mt-0.5 text-sm leading-[1.5] text-muted-foreground [overflow-wrap:anywhere] [&_.sf-entity]:text-inherit [&_.sf-entity]:font-normal"
    >
        <slot v-if="hasContent(slots.default?.() ?? [])" />
        <template v-for="part in roles" :key="part.role">
            {{ ' · '
            }}<span class="sf-meta__role"
                >{{ part.word + ' '
                }}<template
                    v-for="(entity, index) in part.entities"
                    :key="entity.id"
                    ><EntityLink :entity="entity" /><template
                        v-if="
                            part.overflow === 0 &&
                            index === part.entities.length - 2
                        "
                    >
                        and </template
                    ><template v-else-if="index < part.entities.length - 1"
                        >,
                    </template></template
                ><template v-if="part.overflow > 0">
                    and {{ part.overflow }} more</template
                ></span
            >
        </template>
    </div>
</template>
